INSERT INTO `mywords`(`up`, `w`, `p`, `m`) VALUES
(0,'Altı Çub Soğdak bodun','','coğda dövlən nəzərdə tunilur,'),
(0,'Apar','','avar, türklərdən qərbdə yaşayan xalg'),
(0,'Apurım','','səhv oxudur: əslində Ara Urum olmalıdır. Kül tigin abidəsində bu ad apar: "avar" etnonimindən sonra çəkilir, deməli, ә, avarlara nisbətən qərbdə yerləşir. Buna görə də mən onu Apa Urum  - Böyük Roma kimi oxuyuram. Mən belə güman edirəm ki, bu, Bizansa (Vizantiyaya) verilən addır. Buradan mən belə nəticəyə gəlirəm ki, Kül tiginin dəfnində Vizantiya nümayəndə heyəti də iştirak etmişdir.'),
(0,'Az','','Kögmən dağlarında yaşayan xalq'),
(0,'Basmıl','','Çim dilmdə pa-si-mi, türkdilli qəbilədir.'),
(0,'Bukarak','','Orta Asiyada Buxara ulusu, Buxaralılar, güman ki, soğd dilində danışmışlar.'),
(0,'Bayırku','','türklərdən şimalda yaşayan xalq, türkdilli qəbilədir: Çin dilində pa-ye-ku adlanır.'),
(0,'Çik','','Kögmən meşəli dağlarında yaşayan türkdilli qəbilənin adı. Məncə, çiklər müasir tuvalıların ulu babalarıdır.'),
(0,'Çigil','','türkdilli qəbilənin adı'),
(0,'Ediz','','oğuz xalqına daxil olan bir qəbilə,'),
(0,'Edizkər','','ediz qəbilə ittifaqına daxil oları soy'),
(0,'İzgil','','oğuz xalqına daxil olan bir qəbilə'),
(0,'Kənərəs','','kəngər qəbiləsinin adı, rus mənbələrində kanqı termini ilə verilir. Kəngərlərin eramızdan əvvəl P əsrdə SırDərya çayının orta vә aşağı axarında güclü dövlətləri olmuşdur. Çin səfiri Çjan Tsyan eramızdan avvəl 128-ci ildə Kəngər dövlətinin paytaxtında olmuşdur. Kəngərlərin  hakimiyyəti qərbi Xəzər və Volqa çayınadək yayılırdı. Eramızın I əsrində kəngərləri peçeneq adlandırmışlar.'),
(0,'Kök türk','','göy, mavi türk: eramızın ÜI əsrində Monqolustanın şimalında qüdrətli хаqanlıq yaratmış türk qəbilələrinin başında duran qəbilə ittifaqı, Türk xaqanlığının sərhədləri şərqdən Mancuriyadan qərbdə Don çayının arxasinadək, şimaldan Baykal gölü sahillərindən cənubda Tibetədək böyük bir ərazini tuturdu.'),
(0,'Kürt','','türkdilli qəbilədir'),
(0,'Kabay','','dil mənsubiyyəti məlum olmayan qəbilə'),
(0,'Kara türgiş','','qərbi göy türklərə daxildir.'),
(0,'Karluk','','Altayda yaşayan türk xalqı, Üç böyük qəbilədən ibarətdir'),
(0,'Kıbçak','','qıpçaq qəbiləsi. Ərəb mənbələrində kıpçak, rus mənbələrində poloves, qərb mənbələrində kuman adlanır. Qıpçaqlar Altay dağlarından Dunay çayının mənsəbinədək Qazaxıstan, Volqaboyu və Şərqi Avropa düzənliyində yaşamışlar, Qıpçaqlar bir sıra türk xalqlarının, o cümlədən azərbaycanlıların təşəkkülündə böyük rol oynamışlar.'),
(0,'Kırkız','','Yenisey çayının yuxarilarında  Kem və Kemçik çayları hövzəsində yaşamış türk xalqıdır. Kırkızlar: 840-ci: ildə uyğurları (Uyğur xaqanlığını) məğlub edib Mərkəzi Asiyada qüdrətli dövlət-Kırğız xaqanlığını yaratmışlar.'),
(0,'Kıtay','','Mərkəzi Asiyada xalq, 405-ci ildən belə adlanır: rus mənbələrində kidanı adlanan bu xalq müasir tanqutların ulu babalarıdır.'),
(0,'Oğuz','','oğuzlar Şərqi Hun ittifaqına daxil olmuşdur. Orxon abidələrində oğuzlar gah Bilgə xaqanın öz xalqı, gah da düşməni adlandırılır. Oğuzlar müasir azərbaycanlı, türk və türkmənlərin ulu babalarıdır.'),
(0,'On ok','','Qərbi göy türklərə verilmiş addır.'),
(0,'On uyğur','','Ön boydan ibarət olan uyğurlar'),
(0,'Otuz tatar','','Türk xaqanlığı dövründə monqoldilli qəbilə olmuşdur. Sonralar bu qəbilə türkləşmişdir.'),
(0,'Səkiz oğuz','','səkkiz boydan ibarət oğuz qəbiləsi'),
(0,'Soğdak','','soğd xalqı'),
(0,'Suğd/Soğd','','soğd xalqı'),
(0,'Tabğaç','','türklərin çinlilərə verdiyi ad, Əslində tabğaclar çinli olmamış, türkdilli müstəqil xalq olmuşdur. Tabğaclar şimali Çini işğal etmiş, onlara qarışmış və Çin dilini qəbul etmişlər. Türklər də çinliləri onların öz həqiqi adı ilə deyil, tabğacların adı ilə tanımışlar,'),
(0,'Tanut','','süs mənbələrində tanqut adlanır; türk qəbilələrindən birinin adı'),
(0,'Tarduş','','Şərq Türk xaqanlığının qərbində yaşayan türk qəbiləsinin adıdır. Türk xaqanlığında tarduşlar mühüm rol oynamışlar. Türk xaqanlığının taxtına oturmamışdan tarduşların şadı olmaq lazım idi. Bilgə xaqan da axta çıxmazdan əvval 19 4 tarduşlar üzərində şad olmuşdur.'),
(0,'Tatar','','monqoldilli qəbilənin adıdir. Örxon-Yenisey abidələrində adları tez-tez çəkilir, Çin mənbələrində tatarların adı IX əsrin ortalarından (ta-ta şəklində çəkilir. Tatarlar sonralar türk- ləşmişlər'),
(0,'Tatabı','','üç hissəyə ayırılan Kıtayların sonralar çinlilər tərəfindən hi adı verilmiş ki-mo-hi qəbiləsi'),
(0,'Tezik','','türklərin ərəblərə yaxud ümumiyyətlə müsəlmanlara verdikləri ad, fonetik tərkibinə görə tacik sözünə də yaxındır. Buna göro də mən önü tacik kimi qəbul etməyə meyl edərdim.'),
(0,'Tokar','','toxarlar. Toxarlar Şərqi Türküstanda yaşamışlar. Toxar dili Hind-Avropa dilləri ailəsinə daxildir. Həmin ailəyə daxil olan 12 dil qrupundan birini təşkil edir. Hazırda bu dildə heç kim danışmır (ölü dildir).'),
(0,'Tokuz tatar','','monqolların bir qəbiləsi'),
(0,'Tonra','','(türk qəbilələrinin bir boyu, oğuz qəbilə ittifaqına mənsub olduğu da güman edilir.'),
(0,'Töliş','','türkdilli gəbilədir, göy türk xaqanlığına daxil olmuşdur. Çin dilində The-le şəklində yazılır.'),
(0,'Tüpüt','','tibet xalqı və Tibet dövləti, türklərdən cənubda yerləşir.'),
(0,'Türgiş','','qərbi göy türkləri təşkil edən türkdilli qəbilə'),
(0,'Türk','','Kül tigin və Bilgə xaqan abidəsini qoyanlar özlərin: türk, kök türk, kök sir türk bodun (xalq) adlandırırlar. Güman ki, tərkibi yekcins olmamış, tez-tez dəyişmişdir. Belə ki, Bilgə xaqanı eyni bir qəbiləni gah öz türkü, gah yağısı adlandırır.'),
(0,'Uyğur','','Monqolustanın şimalında yaşayan qəbilənin adı, türkdilli gəbilədir. Çin mənbələrində vey-ho, hui-ho və vey-vu-ro şəklində yazllır. Uyğurlar əvvəllər göy türklərə tabe olmuşlar, sonra göy türkləri məğlub edib Selenqa və Tola çayları hövzəsində yaşamışlar. Onlar 630-cu ildə Çinə tabe olmuşlar.'),
(0,'Üç karluk','','Altay dağları və İrtiş çayı hövzəsində yaşayan türkdilli qəbilənin adıdır. Abidələrdə olduğu kimi, Çin mənbələri də onların üç soydan ibarət olduğunu yazır.'),
(0,'ÜÇ kurıkan','','Baykal gölü ətrafinda yaşayan türkdilli qəbilənin adıdır. Üç kurıkanlar sonralar uyğurlara tabe olmuşdur. Güman ki, üç kurıkanlar müasir yaqutların (saxaların) ulu babalarıdır.'),
(0,'Üç oğuz','','üç soydan ibarət olan oğuzlar'),
(0,'Yağma','','türkdilli qəbilədir. ');
