INSERT INTO `mywords`(`up`, `w`, `p`, `m`) VALUES
(0,'о','','nida'),
(0,'obıt','','həya'),
(0,'obratı','','mənasi məlum deyil'),
(0,'oçak','','ocaq'),
(0,'oçuk','','ocaq'),
(0,'od','','od'),
(0,'odğurak','','qəti, açıq, aydın'),
(0,'odğurmak','','oyandırmaq'),
(0,'odğuratı','','qəti anlamaq, tam anlamaq'),
(0,'oduğ','','oyanış'),
(0,'oduğsak','','dirçəliş, sayıq'),
(0,'odun','','günahlı, təqsirli, qəbahətli, suçlu, günahkar'),
(0,'odunmak','','oyanmaq(yuxudan), özünə gəlmək'),
(0,'oduruğ','','ada'),
(0,'oduz','','otuz'),
(0,'oğan','','allah, tanrı'),
(0,'oğatmak','','oyandırmaq'),
(0,'oğlağu','','şəfqətli, zərif'),
(0,'oğlak','','oğlaq, çəpiş, keçi balası'),
(0,'oğlan','','1. gənc adam; 2. oğlan (uşaq)'),
(0,'oğincu','','uşaq kimi qavranılan'),
(0,'oğrak','','məskən'),
(0,'oğramak','','1. rastlaşdırmaq, qarşılamşaq, birləşmək, 2. arzu etmək, tərtib etmək, niyyət etmək'),
(0,'oğrayu','','hələ'),
(0,'oğrı','','oğru, quldar'),
(0,'oğrın','','hiss, həvəs'),
(0,'oğrınta','','uğrunda'),
(0,'oğsamak','','oxşamaq'),
(0,'oğşamak','','oxşamaq'),
(0,'oğul','','oğul'),
(0,'oğulkıya','','1. oğulcığaz, 2. uşaqcasına'),
(0,'oğulluğ','','oğullu, oğula aid, uşağa aid'),
(0,'oğulluk','','oğulluq, övladlıq'),
(0,'oğur','','1. zaman, vaxt; 2. səbəb, fürsət'),
(0,'oğuramak','','niyyət etmək, istəmək'),
(0,'oğurka','','onurğa, partiya'),
(0,'oğurlamak','','oğurlamaq, çalmaq'),
(0,'oğurluğ','','səbəbli'),
(0,'oğurmak','','çalışmaq'),
(0,'oğurta','','vaxtilə, bir zaman'),
(0,'oğurunta','','uğrunda'),
(0,'oğus','','qəbilə, tayfa, soy, nəsil'),
(0,'oğuş','','qəbilə, tayfa, soy, nəsil'),
(0,'oğuşluğ','','qəbiləli, tayfalı, soylu, nəsilli, qəbiləyə mənsub, tayfaya mənsub'),
(0,'oğuz','','ilk süd, ağız'),
(0,'oğuzluğ','','ilk südlü, ağızlı'),
(0,'ok','','1, ox; 2, ədat'),
(0,'okmak','','1. oxumaq; 2. çağırmaq, davam etmək'),
(0,'okıtmak','','oxutmaq, əzbər söyləmək'),
(0,'okışmak','','biri-birini dəvət etmək, biri-birini çağırmaq'),
(0,'oklatmak','','paylaşmaq'),
(0,'oksamak','','oxşamaq, bənzəmək'),
(0,'oksuz','','1. oxsuz, 2. dəstəksiz'),
(0,'okunç','','dəvət, çağırış'),
(0,'okunçsızın','','dəvətsiz, çağırılmadan'),
(0,'okus','','ilk süd, ağız'),
(0,'okusluğ','','ilk südlü, ağızlı'),
(0,'okşağu','','misal, bənzəri, oxşayış, bənzətmə'),
(0,'okşamak','','oxşamaq, bənzəmək'),
(0,'oxşatı','','oxşar, bənzər'),
(0,'okşatığsız','','oxşamayan, bönzəməyən, bənzəri olmayan, oxşarı olmayan'),
(0,'okşatınç','','bənzər'),
(0,'okşatınçsız','','bənzərsiz, bənzəri olmayan'),
(0,'okşatmak','','oxşatmaq, bənzətmək'),
(0,'оl','','о'),
(0,'olar','','onlar'),
(0,'olğurmak','','oturmaq, oturtmaq'),
(0,'olğurtmak','','oturtmaq'),
(0,'oltırık','','sütun'),
(0,'olturmak','','oturmaq'),
(0,'olur','','sap, gövdə'),
(0,'olurmak','','oturmaq'),
(0,'olurtaçı','','oturası, oturan, oturacaq'),
(0,'olursuk','','oturuş, oturma'),
(0,'olyuk','','hadisə'),
(0,'om','','?'),
(0,'on','','on (say)'),
(0,'ona','','bax, məhz'),
(0,'onar','','ona'),
(0,'onınç','','onuncu'),
(0,'onluk','','onluq'),
(0,'onmak','','sağalmaq, şəfa tapmaq'),
(0,'onunç','','onuncu'),
(0,'onçın','','xəstəlik ruhları'),
(0,'on','','1. sağ. 2. (çincə vaznhökmdar) antroponim, şəxs adı'),
(0,'ona','','mətin, dəyanətli'),
(0,'onalı','','bəlli, məlum, açıq'),
(0,'onaltmak','','düzəltmək'),
(0,'onardğu','','asan, yüngül'),
(0,'onardğumak','','asanlaşdırmaq, yüngülləşdirmək'),
(0,'onarmak','','yaxşılaşdırmaq, yaxşı düzəltmək'),
(0,'onaru','','sağa doğru'),
(0,'onay','','asan'),
(0,'onun','','sağdan'),
(0,'ondun','','sağdan'),
(0,'onlium','','incil'),
(0,'onulmak','','yaxşılaşmaq, sağalmaq'),
(0,'onyın','','şeytan'),
(0,'ook','','ox'),
(0,'ooksuz','','1. oxsuz, 2. dəktəksiz'),
(0,'oot','','od, atəş, alov'),
(0,'ootun','','sırtıq, həyasız, utanmaz'),
(0,'opu','','çarx, burulğan, dolambac'),
(0,'or','','taxt (?); "qala" daha uyğundur.'),
(0,'ordu','','orda, saray, ordugah'),
(0,'orğak','','oraq'),
(0,'orın','','yer, mahal, məskən, taxt'),
(0,'ormak','','qoymaq'),
(0,'ornağ','','iqamətgah, taxt'),
(0,'ornağlığ','','1. sağlam, möhkəm, 2. taxtlı, iqamətgahlı'),
(0,'ornağsız','','1. taxtsız, iqamətgahsız, 2. sağlam olmayan, xəstə, daimi olmayan'),
(0,'ornak','','yer, mahal'),
(0,'ornanmak','','qanmaq, yerləşmək, sağlam olmaq'),
(0,'ornaşmak','','yerləşmək, məskun olmaq'),
(0,'оrоһtık','','balıq cinsinin adı'),
(0,'orta','','orta'),
(0,'ortu','','1, orda, saray; 2. orta'),
(0,'ortuk','','1, ada, 2. orlaq'),
(0,'ortuklığ','','ortaqlı, ortaqlıq, dost'),
(0,'оrtun','','ortаnса'),
(0,'oruk','','yol, çarə, imkan'),
(0,'orun','','yer, mahal, məskən, taxt'),
(0,'orunluk','','taxt'),
(0,'orunçak','','əmanət'),
(0,'orun','','bayraq'),
(0,'orunluğ','','bayraqlı'),
(0,'oryan','','çadır'),
(0,'osğun','','ovsun'),
(0,'osğunçu','','ovsunçu'),
(0,'osğunçulamak','','ovsunlamaq'),
(0,'osğurdaçı','','xilaskar'),
(0,'oskurdaçı','','xilaskar'),
(0,'oskurmak','','qurtarmaq'),
(0,'oskuç','','qəssab şagirdi'),
(0,'osmak','','qurtulmaq, xilas olmaq, uzaqlaşmaq'),
(0,'osuğ','','yol, üsul, tərz'),
(0,'osuğluğ','','1.... kimi; 2. yaradılmış, hazırlanmış, 3, üsullu'),
(0,'osulmak','','biçilmək'),
(0,'osuşmak','','peşiman olmaq'),
(0,'oşadıkı','','gərəkli, lazımlı'),
(0,'oşğançulamak','','aldatmaq'),
(0,'oşu','','o'),
(0,'oşul','','о'),
(0,'oşunluğ','','oxşar, bənzər'),
(0,'ot','','od, atəş, ot, bitki, dərman bitkisi'),
(0,'ot','','çarə, vasitə, əlac'),
(0,'otamak','','müalicə etmək'),
(0,'otaçı','','həkim, təbib'),
(0,'otğurak','','sağlam'),
(0,'otğurğah','','ortasındakı'),
(0,'otlamak','','müalicə etmək, baxmaq'),
(0,'otluğ','','odlu, atəşli'),
(0,'ot öçüri','','atəş sönməsi'),
(0,'orta','','orta'),
(0,'otru','','ötrü'),
(0,'otruğ','','аda'),
(0,'otsuz','','1, sağalmaz; 2. çarəsiz, əlacsız, vasitəsiz'),
(0,'otun','','sırtıq, həyasız, utanmaz'),
(0,'otun','','odun'),
(0,'oturuğ','','ada'),
(0,'otuz','','otuz'),
(0,'otuzar','','otuz-otuz'),
(0,'ot yəm','','dərman, əcza'),
(0,'ot yığaç','','ot və ağac'),
(0,'ovusuz','','tərbiyəsiz, utanmaz'),
(0,'ovut','','ədəb, əxlaq, həya'),
(0,'ovutluğ','','həya, həyalı, əxlaqlı, utacaq, əxlaq'),
(0,'ovutsuz','','tərbiyəsiz, utanmaz'),
(0,'oy','','1. qamış, saz, 2. oyuq, çuxur'),
(0,'oymak','','1. oymaq, deşmək, dəlmək, çuxur açmaq, 2 oynamaq'),
(0,'oynamak','','oynamaq'),
(0,'oyuğ','','1. oyun, çalğı çalma, musiqi, rəqs; 2. oyuq'),
(0,'oyun','','oyun'),
(0,'oyunçı','','oyunçu, çalğıçı'),
(0,'ozakı','','keçmiş'),
(0,'ozalamak','','qaçmaq, qabağa keçmək, önə keçmək'),
(0,'ozğu','','xilas'),
(0,'ozğuluğ','','qurtarası, qurtaracaq, xilas olma'),
(0,'ozğuluk','','qurtuluş, xilas olmaq, uzaqlaşmaq'),
(0,'ozğurmak','','qurtarmaq, xilas olmaq'),
(0,'ozğu kurtulğu','','qurtulmuş olan, azad olan'),
(0,'ozmak','','qurtulmaq, xilas olmaq, uzaqlaşmaq'),
(0,'ozkurmak','','qurtarmaq'),
(0,'öbkələmək','','hiddətləndirmək, qəzəbləndirmək'),
(0,'öç','','intiqam, qisas'),
(0,'üçəşçi','','intiqamçı, qisasçı'),
(0,'öçəşmək','','öcəşmək, sataşmaq, kin bəsləmək, çəkişmək'),
(0,'öçlük','','kinli, xain ürəkli'),
(0,'öçmək','','sönmək'),
(0,'öçülmək','','məhv olmaq, bitmək'),
(0,'öçümək','','sönmək, söndürmək'),
(0,'öçür','','sönmə'),
(0,'öçürmək','','söndürmək'),
(0,'öd','','1. vaxt, zaman, 2. nəsihət, öyüd; 3. öd'),
(0,'ödikləmək','','1. öyüd vermək; 2. sevmək'),
(0,'ödirək','','ördək'),
(0,'ödki','','vaxtkı, vaxtda, zamanla əlaqədar'),
(0,'ödkünmək','','ibrət götürmək'),
(0,'ödkürgü','','dərman növüdür'),
(0,'ödkürmək','','öyrətmək'),
(0,'ödləmək','','nəsihət vermək, öyüd vermək'),
(0,'ödmək','','1. çörək, taxıl, 2. keçib getmək, 3. xahiş etmək, diləmək, 4. kəskin olmaq, 5. qəbəlik olmaq'),
(0,'öd kolu','','zaman, dövr'),
(0,'ödrülmək','','ayrılmaq, seçilmək, Torqlənmək'),
(0,'ödsüz','','vaxtsız, zamansız'),
(0,'öd(t)ül','','öskürük'),
(0,'ödük','','öyüd'),
(0,'ödükçi','','öyüdveron'),
(0,'ödügçisiz','','öyüdverəni olmayan'),
(0,'ödün','','vaxt, zaman'),
(0,'ödürmək','','ayırmaq, seçmək, fərqləndirmək'),
(0,'ödüş','','nəmli, yaş, rütubətli'),
(0,'ödvi','','sərt'),
(0,'ödvilig','','sərt olan'),
(0,'ög','','1, ana, 2, ağıl, idrak, zəka, 3. bir çiçək adı'),
(0,'ögdi','','mədh, tərif, öymə'),
(0,'ögdilik','','tərifə layiq, alqışa layiq'),
(0,'ögdir','','qiymət, dəyər'),
(0,'ögdisiz','','tərifə layiq olmayan'),
(0,'ögdü','','tərif, alqış, mədh, öymə, təqdir'),
(0,'ögdünki','','öndəki'),
(0,'ögdüş','','paz'),
(0,'ögə','','1, müdrik, bilici, aqil, ağıl verən, tərbiyə verən; 2. nazir, vəkil, həkim; 3. şöhrət'),
(0,'Ögdəy','','antroponim, kişi adı'),
(0,'ögək','','sevimli, can atan, düşündürən, dilbər'),
(0,'ögən','','1 dərə, 2. çay'),
(0,'ögərətik','','iəlim, tərbiyə, öyrətmə'),
(0,'ögənkiə','','dərəcik'),
(0,'ögimək','','böyümək, artmaq, yüksəlmək'),
(0,'ögirmək','','öyünmək, sevinmək, şadlanmaq, nəşələnmək'),
(0,'ögirtürmək','','sevindirmək'),
(0,'ögitmək','','1. öymək, tərifləmək, mədh etmək, 2. böyütmək, çoxaltmaq, artırmaq'),
(0,'ögləmək','','nəsihət vermək'),
(0,'ögləndürmək','','nəsihət verilmək, ağlını başına toplamaq'),
(0,'öglənmək','','ağıllanmaq, ağlını başma yığmaq'),
(0,'ögləntürmək','','nəosihəl vermək, ağlını başına yığmaq'),
(0,'ögləşmək','','1. məsləhətləşmək, 2. vuruşmaq'),
(0,'ögli','','ağıllı, düşüncəli, zəkalı, dərrakəli'),
(0,'öglimək','','böyümək, çoxalmaq, artmaq'),
(0,'öglük','','analı, anası olan'),
(0,'ögmək','','1. öymək, tərifləmək, alqışlamaq, 2. düşünmək, 3. əzmək, incəltmək, ovmaq'),
(0,'ögmiş','','öymə, tərif, alqış, mədh'),
(0,'ögrənmək','','alışmaq, öyrənmək'),
(0,'ögrənmiş','','alışmış, öyrəşmiş'),
(0,'ögətdəçi','','öyrədən, təlim verən, məşqçi'),
(0,'ögrətig','','adət, təlim, bilik, alışma'),
(0,'ögrətinmək','','öyrədilmək, təlim verilmək, təlim görmək'),
(0,'ögrətmək','','öyrətmək, təlim vermək'),
(0,'ögri','','vaxt, zaman'),
(0,'ögrinçlig','','sevincli'),
(0,'ögrünç','','1. sevinc; 2. antroponim, şəxs adı'),
(0,'ögrünçü','','sevincli, fərəhli'),
(0,'ögrünçüləgülüg','','sevinməli, əylənməli'),
(0,'ögrünçüləmək','','sevinmək, əylənmək, şadlanmaq, fərəhlənmək'),
(0,'ögrnünçülənmək','','sevinmək, əylənmək, şadlanmaq, fərəhlənmək'),
(0,'ögrünçülüg','','sevincli, fərəhli'),
(0,'ögrünçüligin','','sevinclə, sevinə-sevinə, fərəhlə'),
(0,'ögsirəmək','','ağlını itirmək'),
(0,'ögsüz','','1. anasız, 2. ağılsız, idraksız'),
(0,'ögsük','','ağıllı'),
(0,'ögsümək','','əsirgəmək'),
(0,'ögüz','','çay'),
(0,'ögük','','sevimli, can alan'),
(0,'ögülüg','','düşünən, fikirləşon'),
(0,'ögünmək','','peşiman olmaq'),
(0,'ögünç','','sevic, fəoroh, nəşə'),
(0,'ögür','','ilxı, sürü'),
(0,'ögürmək','','öyünmək, özünü öymək, qürrələnmək'),
(0,'ögüt','','öyüd, nəsihət'),
(0,'ögütmək','','öymək, nəsihət vermək, öyüd vermək'),
(0,'ögüç','','anacıq'),
(0,'ök','','əlbəttə'),
(0,'ökən','','çay'),
(0,'ökimək','','artmaq, böyümək, yüksəlmək'),
(0,'ökləmək','','artmaq, çoxalmaq'),
(0,'ökmək','','öymək, tərifləmək, alqışlamaq'),
(0,'ökrəm','','xəndək'),
(0,'ökük','','sevimli, dilbər, can alan'),
(0,'öküknək','','peşmanlıq'),
(0,'ökümək','','anlamaq'),
(0,'ökünç','','peşmanlıq'),
(0,'ökünçsiz','','peşmansız'),
(0,'öküngü','','peşman olmaq'),
(0,'ökünmək','','peşman olmaq'),
(0,'öküs','','çox'),
(0,'öküş','','. çox'),
(0,'öküşti','','bolluca, çoxluca, sıx-sıx'),
(0,'öküz','','öküz'),
(0,'öl','','yaş, rütubət, nəm'),
(0,'ölən','','rütubətli yer, bataqlıq arası'),
(0,'ölənlik','','otlaq, çəmənlik'),
(0,'ölgünlük','','can, çəkişən, can verən, ölüm ayağında olan'),
(0,'ölmək','','ölmək'),
(0,'ölmək əmgək','','ölüm, can çəkişmə (hərfən; ölmək əzabı)'),
(0,'ölməklig','','ölümlü, fani'),
(0,'ölüg','','ölü, cəsəd'),
(0,'ölüm','','ölüm'),
(0,'ölümçü','','öləsi, ölümə məhkum'),
(0,'ölümlig','','ölümlü'),
(0,'ölürgü','','öldürmə'),
(0,'ölürgüçi','','qatil, qanlı'),
(0,'ölürmək','','öldürmək'),
(0,'ölürtmək','','öldürtmək'),
(0,'ölüt','','öldürmə, qətl etmə'),
(0,'ölütçi','','qatil, qanlı'),
(0,'ölütlik','','sallaqxana'),
(0,'öm','','alt paltar'),
(0,'ömək','','xatırlamıaq, düşünmək'),
(0,'ömək','','1. xərçəng (xəstəlik); 2, sağalmaz dəri xastəliyi'),
(0,'ömgəkləmək','','iməkləmək, sürünmək'),
(0,'ömgən','','boğaz arteriyası, boyun arteriyası'),
(0,'öndürmək','','böyütmək, yoluna qoymaq, alınacaqları toplamaq'),
(0,'önəmək','','yüksəlmək'),
(0,'öngü','','bala, dayça'),
(0,'önləmək','','inkişaf etmək, irəli getmək'),
(0,'önlük','','uca'),
(0,'önmək','','çıxmaq, qalxmaq, yüksəlmək, yaymaq, törəmək, ucalmaq'),
(0,'önmən','','sağalmaz bir dəri xəstəliyi'),
(0,'öntürmək','','göndərmək, uzaqlaşdırmaq'),
(0,'önünç','','uca'),
(0,'önünçsüz','','uca olmayan, alçaq'),
(0,'önüş','','yüksəlmiş, çıxış'),
(0,'önüşlüg','','yüksəlişli, qalxılacaq, çıxrlacaq'),
(0,'ön','','1. rəng; 2. ön tərəf, ön, şərqə qarşı'),
(0,'önədəmək','','1. dəyişmək, 2. yaxşılaşmaq, sağalmaq'),
(0,'önətdürmək','','1. dəyişmək; 2. yaxşılaşmaq, sağalmaq'),
(0,'önətmək','','1. dəyişmək, 2. yaxşılaşmaq, sağalmaq'),
(0,'öndin','','öndən'),
(0,'öndüri','','öndən, qarşıdan, şərqdən'),
(0,'öndürti','','öndən, qarışıdan'),
(0,'öni','','artıq, fərqli, hər növ'),
(0,'öni-öni','','1. növ-növ, 2. parça-parça'),
(0,'önişük','','fərqlənən (?)'),
(0,'önlüg','','rəngli'),
(0,'önlük','','üz, çöhrə, sifət, sima'),
(0,'önrə','','1. önçə, qabaqca, əvvəlcə, vaxtilə; 2, irəlidə, şərqdə, şərqə'),
(0,'önrəkitə','','qabaqcadan, irəlicədən, əvvəlcədən'),
(0,'önsüz','','rəngsiz'),
(0,'öntürmək','','uzaqlaşdırmaq, göndərmək'),
(0,'önü','','əvvəlki, qabaqkı'),
(0,'önüç','','boğaz, xirtdək, qırtlaq'),
(0,'önüki','','başqa'),
(0,'öp','','də'),
(0,'öpəlmək','','yanmaq, alovlanmaq, parlamaq'),
(0,'öpgü','','öpüş'),
(0,'öpişmək','','öpüşmək'),
(0,'öpkə','','1. kin, qəzəb; 2. ciyər'),
(0,'öpkəçi','','qəzəbli, kinli, hirsli'),
(0,'öpüksəmək','','öpmək istəmək'),
(0,'öpünmək','','hücum etmək'),
(0,'öpüp','','hop-hop quşu (əslində "öp-öp" olmalıdır)'),
(0,'ördünmək','','örtünmək'),
(0,'öri','','yüksək, vacib, ləyaqətli'),
(0,'öritməgü','','bəsləmə'),
(0,'öritməgüçi','','bəsləyən (adam)'),
(0,'öritmək','','yüksəltmək, bəsləmək'),
(0,'örgin','','taxt'),
(0,'örgün','','taxt'),
(0,'örgüt','','daim, hər vaxt'),
(0,'örki','','uca, yüksək, ali'),
(0,'örlədmək','','incitmək, hiddətləndirmək, əsəbiləşdirmək'),
(0,'örləmək','','1. hiddətləndirmək, qəzəbləndirmək, gurlamaq; 2. yüksəlmək'),
(0,'örlətişmək','','qızışmaq'),
(0,'örlətmək','','hiddətləndirmək, qəzəbləndirmək, incitmək'),
(0,'örlüşmək','','didişmək'),
(0,'örmək','','1. yüksəlmək, çıxmaq, 2. paltar adıdır'),
(0,'örmən','','sağalmaz dəri xəstəliyi'),
(0,'ört','','alov, yanğın, od, atəş'),
(0,'örtəmək','','tutuşdurmaq, yandırmaq'),
(0,'örtən','','alov, yanğın'),
(0,'örtənmək','','1. alovlandırmaq, yandırmaq, qovurmaq; 2. kədərlənmək'),
(0,'örtgü','','örtü, örtük'),
(0,'örtkü','','örtü, örtük'),
(0,'örtlədəçi','','yandıran (adam)'),
(0,'örtləmək','','yandırmaq, alovlandırmaq'),
(0,'örtlüg','','alovlu, odlu, atəşli'),
(0,'örtlük','','alovlu, odlu, atəşli'),
(0,'örtmək','','örtmək, qapamaq'),
(0,'örtük','','örtük'),
(0,'örtüglüg','','örtülmüş, gizli'),
(0,'örtülmək','','örtülmək'),
(0,'örtünmək','','örtünmək'),
(0,'örtüntəg','','dərman adıdır'),
(0,'örtüntəgsiz','','əlacsız'),
(0,'örtürmək','','sürdürmək, yüksəltmək'),
(0,'örü','','yuxarı, dik, yoxuş'),
(0,'örüg','','əbədi, uzun müddət'),
(0,'örüki','','uca, yüksəkdəki, ali'),
(0,'örük uzatı','','davamlı, sürəkli'),
(0,'örün','','açıq rongli, ağımtıl'),
(0,'örütmək','','bəsləmək, yüksəltmək'),
(0,'örüş','','yüksəliş, qalxma, yüksəlmə, çıxış'),
(0,'ös','','öz'),
(0,'ösən','','iç, özək'),
(0,'ӧsmək','','şişirtmək'),
(0,'ösürmək','','qabartmaq, şişirtmək'),
(0,'öşə','','qüsur'),
(0,'öşəlig','','qüsurlu'),
(0,'öşəliksiz','','qüsursuz'),
(0,'öt','','1. öyüd, nəsihət, 2. öd'),
(0,'ötəg','','borc'),
(0,'ötəgləmək','','bir iş görmək'),
(0,'ötəgçi','','borclu'),
(0,'ötək','','borc'),
(0,'ötəkşi','','borçlu'),
(0,'ötəmək','','1. ödəmək (borcu), 2. müraciət etmək, 3. nəşət etmək, çıxmaq'),
(0,'ötkürmək','','işləmək'),
(0,'ötkürü','','sonra, dolayısı ilə'),
(0,'ötig','','siyahı'),
(0,'ötgü','','ötmə, keçmə'),
(0,'ötgün','','ölgün, ötmüş, keçmiş'),
(0,'ötgürmək','','nüfuz etmək, uğurlamaq'),
(0,'ötgürü','','sonra, dolayısı ilə'),
(0,'ötgürü satmak','','alver etmək, alıb satmaq'),
(0,'ötgüçü','','ötən, keçən'),
(0,'ötkürünç','','nüfuz'),
(0,'ötkürünçsiz','','nüfuzsuz'),
(0,'ötləmək','','öyüd vermək, nəsihət vermək'),
(0,'ötmək','','1, çörək, taxıl, 2. ötmək, keçib getmək; 3. xahiş etmək, diləmək, 4. kəskin olmaq; 5. qəbəlik olmaq'),
(0,'ötmiş','','qurban, qurbanlıq'),
(0,'ötrü','','ötrü, üçün, görə, sonra, o zaman'),
(0,'öttrü','','ötrü, üçün, görə, sonra, o zaman'),
(0,'ötüg','','qısaboğaz çəkmə, ayaqqabı'),
(0,'ötüg','','1. dilək, dua, sual; 2. ayaqqabı'),
(0,'ötügçi','','xahişçi, diləkçi, xahiş edən'),
(0,'ötün','','aciz'),
(0,'ötünmək','','1. peşman olmaq, 2, xahiş etmək, diləmək'),
(0,'ötürmək','','ayırmaq, seçmək, fərqləndirmək'),
(0,'ötürü','','ötrü, üçün, görə, sonra, o zaman'),
(0,'ötürük','','ishal, '),
(0,'övkə','','qəzəb, hiddət, qızma'),
(0,'övkləmək','','qəzəblənmək, qəzəbləndirmək, hiddətləndirmək'),
(0,'övkələnmək','','qəzəblənmək, hiddətionmək'),
(0,'övgəlik','','qəzəbli, hiddətli'),
(0,'övkəsiz','','kinsiz, qəzəbsiz'),
(0,'övkəçi','','qəzəblənən, hiddətlənən'),
(0,'övkiləmək','','qəzəblənmək, hiddətlənmək'),
(0,'öy','','ev'),
(0,'öymək','','fikirləşmək'),
(0,'üyür','','darı'),
(0,'öyürkən','','dərman adı'),
(0,'öz','','1. dərə, 2. öz (əvəzlik)'),
(0,'özə','','üstdə, üstündə, üzərində, yuxarıda'),
(0,'özək','','kiçik dərə'),
(0,'özəki','','fövqəladə, üstün'),
(0,'özələmək','','yüksəlmək, yuxarı qalxmaq, üsto çıxmaq'),
(0,'özələnmək','','yüksəlmək'),
(0,'özəlik','','yüksəklik'),
(0,'özəliksiz','','alçaq, yüksək olmayan, üstün olmayan'),
(0,'özən','','1. tam orta, ən içəri, 2. ilk, öz'),
(0,'öz konuk','','ruh'),
(0,'özirkənmək','','xahiş etmək, geri gətirilmək'),
(0,'özlük','','canlı'),
(0,'özüg','','canlı'),
(0,'özükin','','canını, özünü'),
(0,'özüm','','özüm'),
(0,'özüt','','ruh, can');
