INSERT INTO `mywords`(`up`, `w`, `p`, `m`) VALUES
(0,'bааrs','','bars'),
(0,'baba','','ata'),
(0,'babagir','','həyat, kamat'),
(0,'babakir','','həyat, kainat'),
(0,'baça','','günah'),
(0,'baçağ','','oruc'),
(0,'baçağ','','(orurmak sözü ilə) oruc tutmaq'),
(0,'baçak','','oruc'),
(0,'baçamak','','oruc tutmaq'),
(0,'bad','','bat'),
(0,'badyan','','dərman bitkisinin adı'),
(0,'badmak','','1. batmaq 2. bağlamaq; 3. əkin əkmək'),
(0,'badman','','batman (4 kiloqram)'),
(0,'badruk','','bayraq'),
(0,'badur','','maye ölçüsü'),
(0,'baxıl','','paxıl'),
(0,'bağ','','1 bağ, bənd, 2. boxça, 3. qəbilə, tayfa, 4. bağ, bağça.'),
(0,'bağa','','bağa, qurbağa'),
(0,'bağa','','rütbə dərəcəsi'),
(0,'bağar','','bağır, ürək'),
(0,'bağarsuk','','bağırsaq'),
(0,'bağ borluk','','meynəlik, üzüm bağı'),
(0,'bağır','','1, qara ciyər, köks; 2. sevgili, qohum; 3, dərman adı; 4. qarın, 5. ürək'),
(0,'bağırsak','','İ. bağırsaq, 2. mərhəmət'),
(0,'bağırsuk','','bağırsaq'),
(0,'bağış','','qalın yorğan, xalat'),
(0,'bağlığ','','1. bağlı, 2. bağlı, örtülü, tutulu; 3, boxça, paket'),
(0,'bağrağu','','uyğunsuz'),
(0,'bağrın','','bağır ilə'),
(0,'bağsal','','bağı (ipi) olan'),
(0,'baxıllık','','paxıllıq'),
(0,'bak','','bağ'),
(0,'bakanak','','?'),
(0,'bakar','','pul'),
(0,'bakçan','','təfəkkür, mütaliə'),
(0,'bakı.','','1, paxır, 2. güc ölçüsü; 3. sikkə, pül, '),
(0,'bakır','','1, pul, 2. mis'),
(0,'bakırlığ','','puldan düzəldilmiş'),
(0,'bklığ','','?'),
(0,'bakmak','','baxmaq'),
(0,'bakr','','pul (bakır)'),
(0,'bakşı','','1. baxşı, 2. antroponumn'),
(0,'balak','','1, balıq, 2. şəhər'),
(0,'balığ','','1. balıq, 2. şəhər'),
(0,'balığça','','balıq kimi'),
(0,'balığçı','','balıqçı'),
(0,'balık','','1. balıq; 2. şəhər'),
(0,'balık bəgi','','şəhər bəyi, vali'),
(0,'balıklığ','','şəhərli'),
(0,'balıkçı','','balıqçı'),
(0,'balınlamak','','yuxuda qorxudan sıçramaq, diksinmək'),
(0,'baltır','','baldız'),
(0,'balu','','bağlayır '),
(0,'bamak','','bağlamaq'),
(0,'ban','','1. yazı taxtası, 2. on min'),
(0,'banıt','','şurup'),
(0,'banmış','','xəstəlik adıdır'),
(0,'bantın','','oturmağa məxsus sıra var, mövcud olma'),
(0,'bara','','1. dərman adı; 2. güc ölçüsü'),
(0,'bar(a)m','','zənginlik, var-dövlət, sərvət'),
(0,'baram','','zənginlik, var-dövlət, sərvət'),
(0,'baramlığ,','','zənginlik, varlıq'),
(0,'baramit','','çarə yolu'),
(0,'barça','','hamısı, tamam'),
(0,'barçın','','qumaş növü'),
(0,'barğu','','1. getmə, 2. varmı'),
(0,'barğuçı','','gedən (adam)'),
(0,'barığ','','1. gediş, 2. yürüş'),
(0,'barığsamak','','getmək istəmək'),
(0,'barılmak','','getmək'),
(0,'barım','','zənginlik, dövlət, varlıq'),
(0,'barımlığ','','zəngin'),
(0,'barm','','dövlət, var'),
(0,'barınmak','','boşanmaq, azad olmaq'),
(0,'bark','','saray, ev, mülk'),
(0,'barku','','şeypur'),
(0,'barmak','','getmək, varmaq'),
(0,'bars','','1. bars, 2. il adı, antroponim, xüsusi ad'),
(0,'bartmak','','qırmaq'),
(0,'baru','','dolayısı'),
(0,'barhasuvadi','','Yupiter'),
(0,'barz','','bars'),
(0,'bas','','baş'),
(0,'basa','','başqa'),
(0,'basa basa','','durmadan'),
(0,'basdıkmak','','basılmaq, məğlub olmaq'),
(0,'basğuk','','qaya, dağ parçası, yoğunluq'),
(0,'basığsız','','minnətsiz'),
(0,'basık','','vergi adı'),
(0,'basınmak','','basmak, əzmək'),
(0,'basınturmak','','basdırılmaq'),
(0,'basınç','','basqın'),
(0,'basınçsız','','basqın olmadan'),
(0,'basınçı','','təsir, təzyiq'),
(0,'basıtmak','','basılmaq, təzyiq edilmək'),
(0,'baskan','','basan, əzən'),
(0,'baskuk','','1. qaya parçası, 2. milli marş'),
(0,'basmak','','1. yaymaq, 2. basmaq, qazanmaq'),
(0,'bastıkmak','','basılmış olmaq'),
(0,'basudmak','','başçılıq etmək'),
(0,'basudçı','','başçı, rəhbər'),
(0,'basudçılığ','','başçılığ, rəhbərlik'),
(0,'basuk','','zirvə (dağ zirvəsi)'),
(0,'basurmak','','əzmək, basmaq, qalib gəlmək'),
(0,'basut','','yardım, kömək'),
(0,'basutçı','','yardımçı, köməkçi, qoruyucu, arxa, hami'),
(0,'baş','','1. baş; 2. yara, yara başı, 3, başlanğıc, birinci, ilk'),
(0,'başağut','','sevilən, başda gələn'),
(0,'başamak','','üstün gəlmək'),
(0,'baş bitig','','baş sənəd'),
(0,'başçı','','ilk yol açan'),
(0,'bat','','dərhal'),
(0,'başdınkı','','ilk, birinci, başdakı'),
(0,'başık','','nəğmə, şərqi'),
(0,'başkarmak','','rəhbərlik etmək'),
(0,'başlağ','','başlanğıc'),
(0,'başladaçı','','başçı, rəhbər'),
(0,'başlamak','','başlamaq'),
(0,'başlanmak','','başlanmaq'),
(0,'başlataçı','','başçı, rəhbər'),
(0,'başlığ','','başlı, yararlı'),
(0,'başsız','','başsız'),
(0,'baştın','','ilk, öncəki'),
(0,'baştınkı','','ilk, birinci, başdakı'),
(0,'baştankıta','','(Saşzankı sözü ilə) hər şeydən qabaq, hər şeydən öncə'),
(0,'batatu','','pambıq'),
(0,'batığlığ','','tualet'),
(0,'batılmak','','batmak, batmış olmaq'),
(0,'batır','','1. maye ölçüsü, 2. şal, 3. plaş'),
(0,'batmak','','batınaq'),
(0,'batman','','batman (4 kiloqram)'),
(0,'batsık','','batan, batış, qərb'),
(0,'baturmak','','gizləmək, saxlamaq'),
(0,'batut','','gizli'),
(0,'bavagir','','həyat, kainat'),
(0,'bavşın','','varis, vərəsə'),
(0,'bay','','varlı'),
(0,'baya','','öncə, əvvəlcə'),
(0,'bayağır','','həyat, kainat'),
(0,'bayağut','','varlılar, dövlətlilər'),
(0,'bayağuş','','varlı'),
(0,'bayakı','','bir az ovvəlki, bayaqkı'),
(0,'bayakut','','varlı'),
(0,'bayımak','','varlanmaq'),
(0,'baymak','','bağlamaq'),
(0,'baz','','tabe'),
(0,'bazğan','','basan, əzən'),
(0,'heçəl','','yazıq, məzlum, köməksiz, əlsiz-ayaqsız'),
(0,'bedümək','','böyümək'),
(0,'bekrək','','qüdrətli'),
(0,'belindək','','iflic'),
(0,'belgü','','əlamət, rəmz, simvol, işarə'),
(0,'belgülük','','əlamətli, tanınan, görünən'),
(0,'belgümək','','tanınmaq, görünmək'),
(0,'belgürmə','','görünmə, ortaya çıxma, zahirə çıxma, zühur'),
(0,'belgürmək','','görünmək, ortaya çıxmaq, zahirə çıxmaq, zühur etmək, məlum olmaq'),
(0,'belgürtmək','','bəlli etmək, məlum etmək, aşkar etmək'),
(0,'belgüsüz','','əlamətsiz, nişanəsiz'),
(0,'bergən','','verən'),
(0,'bermək','','vermək'),
(0,'bertük','','chtiyacı olan, möhtac'),
(0,'bədiz','','bəzək, şəkil, rəsm, təsvir'),
(0,'bədizəmək','','bəzəmək'),
(0,'bədizən mək','','bəzənmək'),
(0,'bədizədmək','','bəzətmək'),
(0,'bədizətmək','','bəzətmək'),
(0,'bədizmək','','bəzəmək'),
(0,'bədizçi','','rəssam, daş yonan, həkkak'),
(0,'bədük','','böyük, yüksək, ulu, əzəmətli'),
(0,'bədürləmək','','böyümək, yüksəlmək'),
(0,'bədürlənirmək','','böyütmək'),
(0,'bədümək','','böyümək, çoxalmaq'),
(0,'bədürmək','','böyütmək'),
(0,'bədütmək','','böyütmək, yüksəltmək'),
(0,'bəg','','1. böy, 2. bəg, ər 1 "şahzadə, 3. kişi dost'),
(0,'bəgədmək','','bəy adı vermək, beylik etmək, hökm etmək'),
(0,'bəgətmək','','bəy adı vermək, bəylik etmək, hökm etmək'),
(0,'bəgidmək','','bəy etmək, bəy adı vermək, hökm etmək'),
(0,'bəgiz','','zühur, aşkara çıxma'),
(0,'bəgimsinmək','','özünü bəy hesab etmək'),
(0,'bəglig','','bəyli, bəylik, bəy tayfasından'),
(0,'bəgni','','pivə'),
(0,'bəgrə','','dəyənək'),
(0,'bəgrək','','bəy, şahzadə'),
(0,'bk','','bək (7)'),
(0,'bək','','sağlam, yaxşı, bərk, sərt'),
(0,'bəkiz belgülük','','açıq, bəlli'),
(0,'bəkili','','birə'),
(0,'bəkini','','birə'),
(0,'bəkirə','','sağlam, güclü, qüvvətli, qüdrətli'),
(0,'bəkləmək','','bağlamaq, kilidləmək, qapamaq'),
(0,'bəklənmək','','bağlanmaq, gilidlənmək'),
(0,'bəklətmək','','bağlatmaq, Кәләк'),
(0,'bəklik','','bağlı, kilidii, qapalı'),
(0,'bəkrək','','yaxşı, yüksək, üstün'),
(0,'bəksiz','','arıq, Zəif, gücsüz'),
(0,'bəküdmək','','bərkitmək, sağlamlaşdırmaq'),
(0,'bəkürmək','','bərkitmək, təhkim etmək'),
(0,'bəkürü','','sağlam, bərk, qüvvətli'),
(0,'bəkütmək','','bərkitmək, sağlamlaşdırmaq'),
(0,'bəlin','','qorxu'),
(0,'bəlinləyü','','qorxaraq; qorxu'),
(0,'bəlinləmək','','qorxmaq, hürkmək, qorxudan titrəmək'),
(0,'bəlin,lətmək','','qorxutmaq'),
(0,'bəlin,ə','','qorxma, dönüb qalma'),
(0,'bəltir','','yol qovuşağı, yol ayrıcı'),
(0,'bəltirmək','','yetişmək, ərsəyə çatmaq'),
(0,'bərdinki','','cənubdakı'),
(0,'hərgə','','qamçı, qırmanc'),
(0,'bərgəkmək','','qamçılamaq'),
(0,'hərə','','mil (məsafə/ ölçüsü)'),
(0,'bərişti','','mələk, firiştə'),
(0,'bərk','','1. qüvvətli, güclü, sağlam; 2. meşə, orman'),
(0,'bərkə','','qamçı'),
(0,'bərkirmək','','bərkitmək, sağlamlaşdırmaq'),
(0,'bərklik','','bərklik, bork, möhkəm, sağlam'),
(0,'bərksiz','','1. çürük, sağlam olmayan, bərk olmayan; 2. gücsüz'),
(0,'bərgü','','qamçı, qırmanc'),
(0,'bərgürmək','','qamçılamaq'),
(0,'bərtələmək','','yaralamaq, yıxmaq'),
(0,'bərtinmək','','yaralanmaq, özünü yaralamaq'),
(0,'bərtmək','','qırmaq, parçalamaq'),
(0,'bərtük','','zəkat, parçalanmış'),
(0,'bərü','','bəri, bəriyə'),
(0,'bəsgək','','qızdırma'),
(0,'bəsək','','həromlik'),
(0,'bətük','','böyük, yüksək, ulu, əzəmətli'),
(0,'bətürmək','','böyümək'),
(0,'bəz','','qabarcıq, şiş'),
(0,'bəzək','','bəzək'),
(0,'bəzəklik','','bəzənmə yeri'),
(0,'bəzgək','','qızdırma (xəstəlik)'),
(0,'bəzəmək','','bəzəmək'),
(0,'bəzmək','','titrəmək'),
(0,'bı','','bıçaq, bıçğı'),
(0,'bı bıçku','','bıçaq'),
(0,'bıça','','yırlıq, yırtma'),
(0,'bıçak','','bıçaq'),
(0,'bıçğu','','bıçğı, bıçaq'),
(0,'bıçğuluk','','bıçğılı, bıçaqlı'),
(0,'bıçılmak','','biçilmək'),
(0,'bıçmaq','','biçmək'),
(0,'bıçtaçı','','cəllad'),
(0,'bıçumak','','kəsmək'),
(0,'bıçuşmak','','kəsişmək'),
(0,'bıdbul','','bibər'),
(0,'bıkın','','xalça'),
(0,'bınıkmak','','yaxşılaşdırmaq, sağaltmaq, şəfa vermək'),
(0,'bırkaru','','cənub'),
(0,'bırtmak','','1. qırmaq, parçalamaq, yaralamaq; 2. şəkil'),
(0,'bışarmak','','ölgünləşdirmək'),
(0,'bışığ','','1. dəymiş, 2. yetkin'),
(0,'bışğunmak','','bişmək, öyrənmək, ölgünləşmək'),
(0,'bışmak','','bişmək, ölgünləşmək'),
(0,'bışrınğu','','soluxan, ölgünləşən'),
(0,'bışrunmak','','soluxmaq, ölgünləşmək'),
(0,'bışurmak','','bişirmək'),
(0,'bitmul','','bibər'),
(0,'biçək','','bıçaq'),
(0,'biçin','','meymun; 2. on iki il siklli türk təqvimində il adı'),
(0,'biçmək','','biçmək'),
(0,'bigü','','hədiyyə, vergi'),
(0,'bid','','1, bit; 2. üz, bəniz, bət'),
(0,'bidig','','1. yazı, 2. böyük, yüksək, ulu, əzəməili'),
(0,'bidilkim','','bir şeyin adıdır'),
(0,'bidgəçü','','katıb, yazı yazan'),
(0,'bil','','bel'),
(0,'bil bağı','','bel bağı, kəmər'),
(0,'bilçə','','belçə, balaca bel'),
(0,'bilgə','','1. müdrik, bilikli; 2. Buğuğ xaqanın adı'),
(0,'bilgürmək','','bildirmək'),
(0,'bilgüçi','','bilən ustad'),
(0,'bilig','','bilik, elm, savad'),
(0,'biligliz','','bilikli, elmli, savadlı'),
(0,'biligsiz','','biliksiz, elmsiz, savadsız'),
(0,'biligsizlik','','biliksizlik, elmsizlik, savadsızlıq'),
(0,'bililmək','','bilinmək, tanınmaq'),
(0,'bilinmək','','bilinmək, tanınmaq, anlaşılmaq, etiraf etmək'),
(0,'biliş','','bilmə'),
(0,'bilmək','','bilmək, tanımaq'),
(0,'bilsinmək','','tanınmış, bilinmiş olmaq'),
(0,'biltizmək','','bildirmək, balli etmək'),
(0,'biltürmək','','bildirmək'),
(0,'bina','','bina, ev'),
(0,'bintipal','','mizraq'),
(0,'bintipalta','','mizraq'),
(0,'bin','','min (say)'),
(0,'bir','','1. bir ( say); 2. cənub'),
(0,'bir-bir','','bir-bir'),
(0,'birdəm','','büsbütün, tamamilə'),
(0,'birə','','mil (məsafə ölçüsü)'),
(0,'birəgü','','bir-bir, birər, biri, birinci'),
(0,'birəgüm','','onlardan biri'),
(0,'birək','','birdən, qəfildən'),
(0,'birər','','birər, bir-bir'),
(0,'birər-birər','','birər-birər, bir-bir'),
(0,'birgə','','qamçı, qırmanc'),
(0,'birgərmək','','çalxalamaq'),
(0,'birgərü','','hamısı bir yerdə'),
(0,'birgin','','ödəmə'),
(0,'birgü','','hədiyyə, vergi'),
(0,'bir ikinti','','bir biri'),
(0,'biri','','bəri, sağ, cənub'),
(0,'birikli','','birikmiş, birləşmiş'),
(0,'birikmək','','birikmək, toplanmaq, birləşmək'),
(0,'birim','','borc'),
(0,'birim alım','','vergi, borc'),
(0,'birimçi','','borclu'),
(0,'birimlig','','borclu'),
(0,'birin birin','','bir-bir'),
(0,'birinç','','birinci'),
(0,'birinçi','','birinci'),
(0,'biriş','','vermə, veriş'),
(0,'birkə','','qamçı'),
(0,'birkələmək','','vermək qabiliyyəti olan'),
(0,'birlə','','ilə, birlikdə, bərabər'),
(0,'birlən','','ilə, birlikdə, bərabər'),
(0,'birməyük','','ödəməyi çatdırmama, verməmə'),
(0,'birmək','','1. vermək; 2. köməkçi fel'),
(0,'bir ödün','','yalnız bir dələ, yalnız bir kərə'),
(0,'birt','','vergi növü'),
(0,'birtək','','bir dəfə, bir yol'),
(0,'birtəm','','birdən, tamamilə, büsbütün'),
(0,'birtəmlədi','','tamamladı, bütünlədi'),
(0,'birtəmlig','','birdəfəlik'),
(0,'birtişmək','','bir-birini cəzalandırmaq'),
(0,'birtmək','','qırmaq, parçalamaq , yaralamaq'),
(0,'birtsiz','','vergisiz'),
(0,'birtürmək','','verdirmək'),
(0,'birük','','əgər, fəqət'),
(0,'birükin','','əgər, fəqət, şayəd'),
(0,'birükiyə','','əgər, fəqət, şayəd'),
(0,'bir yigirmi','','on bir'),
(0,'bir hata','','bir dəfə'),
(0,'bis','','beş'),
(0,'biş','','beş'),
(0,'bişik','','1, beşik, 2. parça, 3. qəbilə, soy, nəsil'),
(0,'bişük','','1. beşik, 2. qəbilə, soy, nəsil'),
(0,'bişük','','bərabər'),
(0,'bit','','1. bit; 2. üz, bəniz, bət'),
(0,'bitgəçi','','yazıçı, katib'),
(0,'bitgəçü','','yaziçi, katib'),
(0,'bitgüçi','','yazıçı, katib'),
(0,'bitig','','1. yazı, kitab, vəsiqə, sənəd, vəsiyyətnamə, 2, hərflər, əlifba'),
(0,'bitigəçi','','yazıçı, katib'),
(0,'bitigüçi','','yazıçı, katib'),
(0,'bitigçi','','yazıçı, katib'),
(0,'bitig taş','','abidə, yazılı daş'),
(0,'bitilmək','','yazılmaq'),
(0,'bitimək','','yazmaq'),
(0,'bititmək','','yazdırmaq, yazdırmaq'),
(0,'biz','','biz ( əvəzlik)'),
(0,'bizin','','bizim'),
(0,'bo','','bu'),
(0,'bod','','1. boy, xalq, camaat; 2, boy, vücud'),
(0,'bodi','','aydınlanma'),
(0,'bodisatv','','bodisatv'),
(0,'hodistv','','bodistv'),
(0,'bodistv','','bodhisattva'),
(0,'bodımak','','asmaq, süzmək, yaxmaq'),
(0,'bolluğ','','boylu'),
(0,'bodostv','','bodisiv'),
(0,'boduğ','','1. göy, boya, xına; 2. heykəl'),
(0,'boduğluğ','','boyalı, rəngli'),
(0,'bodulmak','','asılmaq, bağlanmaq'),
(0,'bodumak','','1. asmaq. süzmək, yaxmaq; 2. boyamaq'),
(0,'bodun','','xalq, qəbilə'),
(0,'bodunlığ','','xalqlı'),
(0,'bodunluğ','','xalqlı'),
(0,'boğa','','buğa, öküz'),
(0,'boğağa','','bənd, qandal, buxov'),
(0,'boğağuluğ','','qandal vurulmuş, qandallı, boğulmuş'),
(0,'boğağulukçı','','cəllad, qatil'),
(0,'boğağuçı','','cəllad, qandal vuran, buxov vuran'),
(0,'boğaz','','1. boğaz, 2, hamilə'),
(0,'boğaz','','(bolmaq sözü ilə) hamilə olmaq'),
(0,'boğdam','','çürümə, iylənmə, iyləmə'),
(0,'boğmak','','boğmaq'),
(0,'boğuk','','boğuq. qapalı'),
(0,'boğuşmak','','boğuşmaq'),
(0,'boğuz','','1. boğaz, 2. heyvanlar üçün əkilmiş taxıl'),
(0,'bok','','yaramaz, rəzil, alçaq, xəbis'),
(0,'bokağu','','buxov, bağ, bənd, zəncir vuran'),
(0,'bokak','','şiş, boğaz uru'),
(0,'boksut','','qayda, nizam, üsul'),
(0,'bokuz','','boğaz'),
(0,'bokuk','','1, Bögü xaqan, 2. şiş, boğaz uru'),
(0,'bokunmak','','çökmək, yerləşmək'),
(0,'bokşut |','','qayda, üsul, nizam'),
(0,'bolğu','','olma'),
(0,'bolğuluğ','','olan'),
(0,'bolğuçı','','olmaq istəyən ( adam)'),
(0,'Boldaz','','antroponim, şəxs adı'),
(0,'bolmak','','olmaq'),
(0,'bolulanmak','','qarışmaq, qarmaqarışıq olmaq'),
(0,'bolulmak','','əldə etmək, tapmaq'),
(0,'bolun','','1. güşə, tərəf, cəhət, 2. dərman;, 3. miqdar ölçüsü'),
(0,'booş','','boş, azad, sərbəsi'),
(0,'bor','','çaxır, şərab'),
(0,'borluğ','','meynəlik, üzüm bağı'),
(0,'borluk','','meynəlik, üzüm bağı'),
(0,'borlukçi','','üzümçü, bağban'),
(0,'borçı','','1. üzümçü, bağban, 2. üzüm vergisi toplayan məmur'),
(0,'bosanmak','','kədərlənmək, mütəəssir olmaq'),
(0,'bosanturmak','','kədərləndirmək, üzmək, üzülmək'),
(0,'bosğak','','pozulmuş, pozulma'),
(0,'boskunmak','','öyrətmək, oxumaq'),
(0,'bosmak','','pozmaq, qırmaq, parçalamaq'),
(0,'bosu','','fasilə'),
(0,'bosuş','','qəm, kədər, qayğı'),
(0,'bosuşluğ','','kədərli, qəmli, qayğılı'),
(0,'boş','','boş, azad, sərbəst'),
(0,'boşanmak','','boşanmaq, azad olmaq, sərbəst olmaq'),
(0,'boş birmək','','yardım etmək, fəda etmək'),
(0,'boş bitig','','azadlıq kağızı ( yazısı)'),
(0,'boşğunmak','','öyrənmək, oxumaq'),
(0,'boşğurmaq','','öyrətmək, dərs demək, oxutmaq, təlim vermək'),
(0,'boşğut','','dərs, təlim, oxuma, öyrənmə'),
(0,'boşğutluğ','','şagird, öyrənən'),
(0,'boğşğutmak','','öyrətmək,oxutmaq'),
(0,'boşğutsuz','','1. təlimsiz; 2. oxumamış, öyrənməmiş'),
(0,'boşğutçı','','müəllim, mürəbbe, öyrədən, təlimatçı'),
(0,'boşuğ','','bağışlama, əfv etmə, azad etmə'),
(0,'boşuğ yarlık','','azadlıq formanı, azadlıq sənədi'),
(0,'boşumaq','','bağışlamaq ( günahı) , qurtarmaq'),
(0,'boşunmağ','','1. boşanmaq, sərbəst olmaq, azad olmaq, 2. tövbə etmək'),
(0,'boşunmak','','1. boşanmaq, sərbəst olmaq, azad olmaq, 2. tövbə etmək'),
(0,'boşurkanmak','','qayğılı olmaq, narahat olmaq'),
(0,'boşurmak','','öyrətmək, dərs demək, oxutmaq, təlim vermək'),
(0,'botulmak','','balalamaq'),
(0,'boy','','boya, rəng'),
(0,'boyın','','boyun, vücud, önsə'),
(0,'boyla','','rütbə adı'),
(0,'boyun','','boyun, vücud, önsə'),
(0,'boyunduruk','','boyunduruq'),
(0,'boyüntrük','','boyunduruq'),
(0,'boz','','1. boz, 2. nifrət, kin'),
(0,'bozoğu','','buzov'),
(0,'bozğak','','pozulmuş, pozulma'),
(0,'bozmak','','pozmaq, qırmaq, parçalamaq'),
(0,'böd','','vaxt'),
(0,'bök','','zindan'),
(0,'böksik','','qarın'),
(0,'böksilmək','','parçalanmaq, yarılmaq'),
(0,'böktə','','xəncər, qılmc'),
(0,'böktəg','','yardım'),
(0,'bökü','','həkm, bilici'),
(0,'bögdə','','xəncər, qılınc'),
(0,'bögrə','','böyrək'),
(0,'bögü','','həkim, bilici'),
(0,'bögülənmək','','güvənmək, etimad etmək'),
(0,'bögülük','','alimlik'),
(0,'bögüş','','elm, hikmət, mərifot'),
(0,'bölmək','','bölmək'),
(0,'bölük','','bölük, hissə'),
(0,'bölüg','','bölük, hissə'),
(0,'böri','','qurd, canavar'),
(0,'börisiz','','düşmənsiz, yağısız'),
(0,'börtmək','','1. toxunmaq, təmasda olmaq, 2. təmas, toxunma'),
(0,'börtülmək','','toxunulmaq'),
(0,'börtün','','məchul, naməlum'),
(0,'börtürmək','','toxundurmaq'),
(0,'böşük','','(tünkür sözü ilə) bərabər qohumluq'),
(0,'böşük körtük','','sevimli, əziz, dost'),
(0,'böz','','bez, pambıq parça'),
(0,'bözçi','','pambıqçı, toxucu'),
(0,'bra','','bra (mənası qaranlıqdır)'),
(0,'braman','','brəhmən'),
(0,'Brahsuvti','','Yupiter planeti'),
(0,'brişti','','mələk, firiştə'),
(0,'bu','','bu (əvəzlik)'),
(0,'budık','','budaq'),
(0,'budın','','bədən'),
(0,'budulmak','','asılmaq, taxılmaq'),
(0,'budun','','qəbilə, xalq'),
(0,'bugün','','bugün'),
(0,'bugünki','','bugünkü'),
(0,'buğan','','noxudkimilər sinfindən bir bitki'),
(0,'buğday','','buğda'),
(0,'buğu','','keyik'),
(0,'buk','','boğaz, xirtdək, qırtlaq'),
(0,'buka','','buğa'),
(0,'bukağu','','buxov, zəncir, qandal, bağ'),
(0,'bukak','','buxaq'),
(0,'bukaç','','çölmək, qazan'),
(0,'bukuklanmak','','yuvarlaşmaq'),
(0,'bukun','','qəbilə, xalq'),
(0,'bulan','','şüşəbənd'),
(0,'bulak','','bulaq'),
(0,'bular','','bunlar'),
(0,'bulayık','','etnonim'),
(0,'bulğağ','','təlatüm; bulanıq; iğtişaş'),
(0,'bulğadaçı','','iğtişaşçı, üsyançı, üsyankar'),
(0,'bulğak','','təlatüm, bulanıq; iğlişaş'),
(0,'bulğamak','','bulamaq, qarışdırmaq, pozmaq'),
(0,'bulğandurmak','','bulandırmaq'),
(0,'bulğanyuk','','bulanıq, qarışıq'),
(0,'bulğanmak','','bulanmaq, qarışdırılmaq, pozulmaq'),
(0,'bulğaşmak','','buluşmaq; toplu halda mövcud olmaq'),
(0,'bulğaşu','','gurultulu'),
(0,'bulğu','','tapıntı'),
(0,'bulğusuz','','tapıntısız'),
(0,'bulıt','','bulud'),
(0,'bulıtçulayu','','buluda bənzər'),
(0,'bulkak','','?'),
(0,'bulkay','','alçaq, aşağı, qısa'),
(0,'bulkamak','','bulamaq, qarışdırmaq, pozmaq'),
(0,'bulkanmak','','bulanmaq, qarışdırılmaq, pozulmaq'),
(0,'bulkumak','','yerinə yetirmək, icra etmək'),
(0,'bulmak','','tapmaq, əldə etmək'),
(0,'bultukbaz','','olmamaq'),
(0,'bultukmak','','əldə edilmək'),
(0,'buluturmaq','','tapdırmaq'),
(0,'bululamak','','qarışmaq'),
(0,'bululmak','','əldə edilmək'),
(0,'bulun','','əsir'),
(0,'bulunç','','1. əldə etmək, qazanc, 2. təmənna'),
(0,'bulunçsız','','1, qazancsız, 2. nadir, tapılmayan, 3. təmənnasız'),
(0,'bulunmak','','əldə etmək'),
(0,'bulun,','','1. guşə, tərəf, cəhət, ətraf, 2. dərman, 3. miqdar ölçüsü'),
(0,'bulut','','bulud'),
(0,'bulhak','','təlatlim, iğtişaş, bulanıq'),
(0,'bun','','əsas, təməl, bünövrə'),
(0,'bun','','dərd, kədər, qüssə'),
(0,'buranç','','sıxıntı, sıxmtılı'),
(0,'burğu','','baraban'),
(0,'burkan','','1. Budda; 2. burhan, 3, yaradan, tanrı, allah, xaliq; 4, şaman'),
(0,'burhan','','burhan (budda dinində ruhani)'),
(0,'burhan kutınlığ','','Budda səadətinə yetişmiş'),
(0,'burhan kutlığ','','Budda bəxtində olan'),
(0,'burkı','','qırış'),
(0,'burkırak','','1. buruq; 2. büzük; 3. qəmgin'),
(0,'burku','','şeypur, boru'),
(0,'burlak','','qoxumaq'),
(0,'burmaduk','','burulmamış'),
(0,'burnaç','','güyüm'),
(0,'bursan','','topa, guruh, camaat'),
(0,'bursin','','rahibələr dərnəyi'),
(0,'burson','','rahibələr dərnəyi'),
(0,'burun','','burun, (fildə) xortum'),
(0,'burunğı','','əvvəlki, öncəki'),
(0,'burunsuz','','burunsuz'),
(0,'buruntuk','','qəm'),
(0,'burunça','','əvvəlki kimi'),
(0,'busanmak','','məyus olmaq, ümidsiz olmaq, acımaq'),
(0,'busat','','oruc adıdır'),
(0,'busi','','sədəqə, qurbanlıq'),
(0,'busuş','','dərd, qəm, kədər, ələm, qayğı'),
(0,'busuşluğ','','dərdli, qəmli, kədərli, qayğılı'),
(0,'busuşsız','','dərdsiz, kədərsiz, qəmsiz, qayğısız'),
(0,'buşdaçı','','pozan, dağıdan, məğlub edən'),
(0,'buşı','','sədəqə, qurbanlıq, nəzir'),
(0,'buşıçı','','dilənçi, sədəqə toplayan'),
(0,'buşılığ','','sədəqəyə möhtac, dilənçi'),
(0,'buşmak','','1. qəzəblənmək, hiddətlənmək, həyəcanlanmaq; 2. pozmaq'),
(0,'buşulmak','','utanmaq'),
(0,'buşunğu','','yeknəsəq'),
(0,'buşunğuluğ','','cansıxan, cansıxıcı'),
(0,'buşurkanmak','','qayğılı olmaq, narahat olmaq'),
(0,'but','','bud, ayaq'),
(0,'butamaq','','budamaq, kəsmək, vurmaq'),
(0,'butarlamaq','','parçalamaq, yırtmaq, parça-paarça etmək'),
(0,'butığ','','budaq'),
(0,'butık','','budaq'),
(0,'butı','','cin, pəri'),
(0,'butluğ','','budlu, ayaqlı'),
(0,'butukmak','','tapılmaq'),
(0,'butulmak','','asılmaq, taxılmaq'),
(0,'buu','','bu'),
(0,'buusı','','dalğın, dağınıq'),
(0,'buvanlığ','','buvanlı (?)'),
(0,'buyanlamak','','yaxşılıq etmək, xidmət etmək'),
(0,'buyanlığ','','xoşbəxt, bəxtli, savablı'),
(0,'buyansız','','bəxtsiz, savabsız'),
(0,'buyançı','','bəxti olan, savab iş görən'),
(0,'buyruk','','əmir, komandan, buyuruq'),
(0,'buz','','pozma, yıxma, dağıtma, təxribat'),
(0,'buz','','buz'),
(0,'buzad','','oruc adıdır'),
(0,'buzağu','','buzov'),
(0,'buzan','','savab, yaxşı iş, yaxşılıq'),
(0,'buzandurmak','','quduzlaşdırmaq'),
(0,'buzandurtaçı','','quduzlaşdıran'),
(0,'buzdaçı','','pozan, qıran, parçalayan'),
(0,'buzluğ','','buzlu'),
(0,'buzmak','','pozmaq, qırmaq, parçalamaq'),
(0,'buzulmak','','pozulmaq'),
(0,'büdimək','','rəqs etmək, ritmik hərəkətlər etmək'),
(0,'büdkər','','yaxşı'),
(0,'büdkərlig','','yaxşılıq'),
(0,'büdkərmək','','tamamlamaq'),
(0,'büdmək','','1. bitmək, sona yetmək, qurtarmaq, tamamlamaq 2. inanmaq'),
(0,'büdün','','bütün'),
(0,'büdürmək','','yerinə yetirmək, tamamlamaq'),
(0,'büdüs','','1. bitkin, yetkin, 2. mam, 3. hikmət'),
(0,'bügri','','əyri'),
(0,'bügü','','hikmət'),
(0,'bügülənmək','','hikmətlənmək, hikmət qazanmaq'),
(0,'bügür','','xalça'),
(0,'bügüş','','hikmət, mərifət'),
(0,'bükən','','qovun növü (yemiş)'),
(0,'bükmək','','bükmək'),
(0,'bükülmək','','bükülmək'),
(0,'bükün','','bugün'),
(0,'bükünki','','bugünki'),
(0,'büküntə','','bugün'),
(0,'bükürmək','','su səpmək'),
(0,'bür','','tumurcuq'),
(0,'büri','','qurd, canavar'),
(0,'bürtmək','','1. hiss etmək, duymaq, toxunmaq; 2. hiss, duyğu 3. xəfifcə əsmək'),
(0,'bürtüglüg','','duyma, hiss etmə'),
(0,'bürtüşmək','','biri birinə toxunmaq'),
(0,'bürü','','qurd, canavar'),
(0,'bürütmək','','1. hiss etmək, duymaq, toxunmaq; 2. hiss, duyğu, 3. xəfifcə əsmək'),
(0,'büşərmək','','təkmilləşdirmək'),
(0,'büşük','','qohumluq'),
(0,'bütkürmək','','bitirmək'),
(0,'bütgü','','bayıra çıxmaq'),
(0,'bütmək','','1. bitirmək, sona yetmək, qurtarmaq, tamamlamaq; 2. inanmaq.'),
(0,'bütüd','','bitmə, famamlama'),
(0,'bütüdmək','','bitirmək, tamamlamaq'),
(0,'bütün','','bütün'),
(0,'bütünmək','','bütöv etmək, tamamlamaq'),
(0,'bütürmək','','bitirmək'),
(0,'bütürü','','tamamilə, hamısı, bütünlüklə'),
(0,'bütüt','','bitmə, tamamlanma'),
(0,'büyü','','cadugərlik, sehirbazlıq'),
(0,'çadar','','kül'),
(0,'çadik','','Sakyamuninin doğum tarixi'),
(0,'çadiklig','','Sakyamuninin doğum tarixi'),
(0,'çadir','','naşatır'),
(0,'çadir','','kül'),
(0,'çadır','','kül'),
(0,'çağ','','çağ, zaman'),
(0,'çağay','','bitki adıdır'),
(0,'çağmak','','vurmaq, çaxmaq'),
(0,'çağrı','','rütbədir'),
(0,'çağurmak','','iftira atmaq, ləkə yaxmaq'),
(0,'çağşaput','','nə isə hindcə termindir'),
(0,'çaidan','','məbəd, ibadətgah'),
(0,'çaidir','','ulduz adıdır'),
(0,'çaitir','','ulduz adıdır'),
(0,'çayti','','monastır'),
(0,'çak','','1, vaxt, zaman; 2. tam'),
(0,'çakı','','gicitkən'),
(0,'çakir','','çarx, təkər'),
(0,'çakmak','','çaxmaq, kəsmək, parçalanmaq, yarmaq'),
(0,'çakr','','çakr (silah adıdır)'),
(0,'çakravat','','dünya'),
(0,'çakşaput','','ay adıdır, Uluqbəy təqvimində 12-ci ay, allah qaydası'),
(0,'çaldr','','dəniz'),
(0,'çalmak','','vurmaq, əyilmək'),
(0,'çalsıkmak','','vurulmuş olmaq'),
(0,'çalturmak','','axtartmaq, aratmaq'),
(0,'çam','','1. dava, etiraz, 2. çanaq, çölmək'),
(0,'çambu','','ağac adı'),
(0,'çambudivip','','kainat'),
(0,'çamlağuçı','','davagu, dava edən, davakar, iddia edən'),
(0,'çamlamak','','dava etmək, çəkişmək, etiraz etmək'),
(0,'çamsız','','davasız, etirazsız'),
(0,'çamxul','','peşman'),
(0,'çan','','1. çən; 2. çanak, bardaq; 3. саn'),
(0,'çanak','','çanaq, qab, ölçü'),
(0,'çantal','','collad'),
(0,'çan','','çan'),
(0,'çanşı','','rütbə adıdır'),
(0,'çao','','sikkə növüdür'),
(0,'çarixuş','','üzüm şirəsi məngənəsi'),
(0,'çarım','','dava, iddia, etiraz'),
(0,'çarlamak','','çağırmaq'),
(0,'çaruk','','çarıq'),
(0,'çası','','ləkə yaxan, iftira atma'),
(0,'çasurmak','','ləkə yaxmaq, iftira atmaq'),
(0,'çasut','','ləkə, iftira'),
(0,'çatik','','doğum hekayəsi'),
(0,'çatık','','yapışmaq'),
(0,'çav','','pul'),
(0,'çavikmak','','1. güclənmək, qüvvətlənmək; 2. məşhur, şöhrətli, adlı-sanlı'),
(0,'çavış','','yol, vasitə, tədbir, hiylə'),
(0,'çavsız','','pulsuz'),
(0,'çau','','həvalə'),
(0,'çeçək','','çiçək'),
(0,'çeçəklənmək','','çiçəklonmək'),
(0,'çeçəklik','','çiçəklik'),
(0,'çəkrək','','alt paltarı'),
(0,'çəkür','','çuxur'),
(0,'çərig','','qoşun, ordu, əskər'),
(0,'çəviş','','yol, vasitə, tədbir, hiylə'),
(0,'çəvişlig','','hiyləli'),
(0,'çxşaput','','əxlaqlı'),
(0,'çhşapat','','əxlaq; orucluq ayı'),
(0,'çhşapatlığ','','əxlaqlı'),
(0,'çığ','','1. bitki adr, 2. arşın'),
(0,'çığay','','yoxsul, fağır'),
(0,'çağsız','','ölçüsüz'),
(0,'çıda','','cida, süngü, mizraq'),
(0,'çıkramak','','qıcırdamaq'),
(0,'çıkratmak','','qıcırdatmaq'),
(0,'çıku','','dərman kimi işlədilən bir daş, mumiya (?)'),
(0,'çımad','','hirs, hiddət, qəzəb, qızışmaq'),
(0,'çımkumak','','(bıçmak sözü ilə) biçmək, kəsmək'),
(0,'çın','','gerçək, çin, doğru'),
(0,'çınaru','','həsrətlə'),
(0,'çınbarmak','','çin, doğru, gerçək'),
(0,'çın bitig','','gerçək sənəd və bağlaşma'),
(0,'çından','','səndəl ağacı'),
(0,'çınğarmak','','araşdırmaq'),
(0,'çınğartmak','','araşdırtmaq, tədqiq etmək, müayinə etmək'),
(0,'çınıkmak','','həyata keçirmək'),
(0,'çınkar','','doğru, tam doğru'),
(0,'çınkaru','','diqqətlə'),
(0,'çın-sav','','gerçək, həqiqət, doğru söz'),
(0,'çınsu','','olduğu kimi'),
(0,'çın','','çin, doğru, gerçək, tam, kəskin'),
(0,'çınarğu','','zil, cingiltili, zəng'),
(0,'çınaru','','1. tam, şübhəsiz; 2. arzulamaq, həsrət'),
(0,'çızdurmak','','cızdırmaq'),
(0,'çızığ','','çizgi, ciziq, hərəkət tərzi'),
(0,'çızmak','','cızmaq'),
(0,'çi','','çin, bilmək'),
(0,'çigidəm','','bitki adıdır'),
(0,'çigil','','etnonim, toponim'),
(0,'çiggmə','','xəstəlik'),
(0,'çiik','','etnonim, çik qəbiləsi'),
(0,'Çiik Tutu','','məmurluq dərəcəsi, ləğəb'),
(0,'çik','','çik qəbiləsi'),
(0,'çikçi','','rütbə adıdır'),
(0,'çiltəg','','etibar, hörmət'),
(0,'çiltəmək','','saymaq, hörmət etmək'),
(0,'çim','','qarışıq, qırış'),
(0,'çimbudip','','kamat'),
(0,'çiməli','','qarışqa'),
(0,'çimgən','','çəmən, çayır'),
(0,'çimsiz','','qırışsız'),
(0,'çin','','çin, gerçək, həqiqət'),
(0,'çintal','','cəllad'),
(0,'çintan','','səndəl ağacı'),
(0,'çintək','','həqiqətə çevirmək'),
(0,'çişt','','ulduz adıdır'),
(0,'çiu','','tutma, yaxalama'),
(0,'çiü','','tutma, yaxalama'),
(0,'çıvğa','','yapışqan sürtülmüş çubuq'),
(0,'çıvğaçı','','(toz sözü ilə) torla ovlayan, duzaq quran'),
(0,'çıvşağun','','turş'),
(0,'çizmək','','cızmaq, çizmək'),
(0,'çkar','','çkar (silah adı)'),
(0,'çkrvrt ilig','','dünya hökmdarı'),
(0,'çtbudvir','','kainat'),
(0,'çobra','','yun'),
(0,'çoğ','','1, qor, köz, od, atəş, ziya, alov, 2. parlaqlıq'),
(0,'çoğı tirək','','rütbə'),
(0,'çoğ yalın','','parlaqlıq'),
(0,'çoğlanmak','','parlamaq'),
(0,'çoğluğ','','nurlu, atoşli, ziyalı, görkəmli'),
(0,'çoğmak','','öldürmək, (heyvanı) kəsmək'),
(0,'çokan kişi','','nişanlı (oğlan, adam)'),
(0,'çokmak','','öldürməx, (heyvanı) kəsmək'),
(0,'çokramak','','qaynamaq'),
(0,'çokratmak','','qaynatmaq'),
(0,'çokurdamak','','qaynatmaq, bişirmək'),
(0,'çolmak','','zədələnmək, lil olmaq'),
(0,'çoluğ','','çolak, əlil'),
(0,'Çoluk','','antroponim, şəxs adı'),
(0,'çomak','','çomaq'),
(0,'çomınmak','','cummaq (suya)'),
(0,'çommak','','batmaq, cummaq (suya)'),
(0,'çumurmış','','maye götürmək üçün çömçə'),
(0,'çonmak','','dözmək, qatlaşmaq, tavlaşmaq'),
(0,'çon','','sol'),
(0,'çor','','rütbə adı'),
(0,'çöbig','','1. çöp, 2. pis, pislik, bulanıq'),
(0,'çökə','','diz çökmə'),
(0,'çökdə','','qulaq arxasındakı çıxıq sümük'),
(0,'çökitmək','','diz çökmək, diz çökdürmək'),
(0,'çökləmək','','çökmək'),
(0,'çökmək','','çökmək'),
(0,'çöktə','','qulaq arxasındakı çıxıq sümük'),
(0,'çöküg','','dizləri çökük'),
(0,'çökütmək','','diz çökdürmək'),
(0,'çökşig','','çökək, zənəxdan'),
(0,'çökməli','','qarışqa'),
(0,'çöp','','şəkil'),
(0,'çrman','','dəri xəstəliyinin bir növü'),
(0,'çu','','1, əkin yeri, tarla, 2. birtərəf etmə, zərərsizləşdirmə'),
(0,'çuanmart','','comərd, mərd'),
(0,'çuba','','cübbə'),
(0,'çubakan','','innab'),
(0,'çubik','','çubuq'),
(0,'çubuyan','','dadlı şey, ləzzətli şey'),
(0,'çubuk','','çubuq'),
(0,'çuğ','','1. bulanığ, 2. bağ, bağça, 3. dəmət, buket'),
(0,'çuğı','','gurultu'),
(0,'çulvu','','(sav sözü ilə) rəzalət, pis şöhrət, küfr'),
(0,'çumburmak','','atılmaq, saldırılmaq'),
(0,'çur','','rütbə, ən böyük hərbi ad (çor olmalıdır)'),
(0,'çurnı','','barıt'),
(0,'çuuğ','','bulanıq'),
(0,'çuv','','hissə, pay'),
(0,'Çüən-tein','','Konfutsinin əsərinin (İlk və son bahar") adı'),
(0,'çügtə','','qulaq arxasındakı çıxıq sümük'),
(0,'çüməli','','qarışaq'),
(0,'çürni','','barıt'),
(0,'çürşət','','xalq, qəbilə'),
(0,'çüsüm','','tut (ağacı)'),
(0,'çüsüm','','(sögüt sözü ilə) ağac növü'),
(0,'çüvit','','göy, mavi'),
(0,'dana','','?'),
(0,'Daniş','','ulduz adıdır'),
(0,'darm','','əqidə'),
(0,'darni','','sehr'),
(0,'dartiraşti','','qəbr dünyasının mühafizi'),
(0,'daruğa','','məmur rütübəsi (müqayisə et; azərbaycanca darğa)'),
(0,'datu','','qəbilə adidir'),
(0,'ddintar','','dindar'),
(0,'dəlik','','dəlik, deşik'),
(0,'dəptər','','dəftər'),
(0,'dıdım','','daş'),
(0,'dın','','din, məzhəb'),
(0,'dındar','','dindar'),
(0,'dıntar','','dindar'),
(0,'dian','','altı yaxud on igiddən biri'),
(0,'didim','','daş'),
(0,'didm','','daş'),
(0,'diyan','','iştirak'),
(0,'din','','din'),
(0,'dindar','','dindar'),
(0,'divdar','','şama oxşayan ağac, sərv ağacı'),
(0,'divini','','allah'),
(0,'doza','','bədənin iksiri'),
(0,'drzul','','yabaya bənzəyən üçdişli alət'),
(0,'drm','','din, əqidə'),
(0,'drma-utari','','bodisatvalardan birinin adı'),
(0,'duşkrçar','','iztirab'),
(0,'dutağun','','günahları bağışlanmış adam'),
(0,'dyan','','təfəkkür'),
(0,'dyanlığ','','fikirli');
